import { defineConfig } from "tsup";

export default defineConfig([
  {
    // CJS config
    entry: ["src/index.ts"],
    format: ["cjs"], // Build only CJS
    dts: true,
    clean: true,
    splitting: false,
    sourcemap: true,
    minify: false,
    define: {
      // Define __dirname_cjs_shim for CJS build
      __dirname_cjs_shim: "__dirname",
    },
  },
  {
    // ESM config (separate config for ESM)
    entry: ["src/index.ts"],
    format: ["esm"], // Build only ESM
    dts: false, // dts already generated by CJS config
    clean: false, // clean already done by CJS config
    splitting: false,
    sourcemap: true,
    minify: false,
  },
]);
